spring:
  profiles:
    active: dev
  application:
    name: Hackathon_De07
  ai:
    openai:
      base-url: https://openrouter.ai/api/v1
      api-key:
      chat:
        model: anthropic/claude-3-haiku
      embedding:
        model: text-embedding-3-small
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        initialize-schema: true
  datasource:
    url: jdbc:postgresql://${database.host}:5432/postgres
    username:
    password:
  #  sql:
  #    init:
  #      mode: always

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
